      edges.push({from: 517, to: 546, title:"from Business Process to Resource:o", label:"",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 520, title:"from Business Process to Capability:r", label:"r",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 524, title:"from Business Process to Course of Action:r", label:"r",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 500, title:"from Business Process to Business Actor:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 518, title:"from Business Process to Business Role:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 511, title:"from Business Process to Business Collaboration:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN}); 
      edges.push({from: 517, to: 515, title:"from Business Process to Business Interface:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 517, title:"from Business Process to Business Process:cfgstv", label:"cfgstv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 513, title:"from Business Process to Business Function:cfgtv", label:"cfgtv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 514, title:"from Business Process to Business Interaction:cfgtv" ,label:"cfgtv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 512, title:"from Business Process to Business Event:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 519, title:"from Business Process to Business Service:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 516, title:"from Business Process to Business Object:a", label:"a",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 523, title:"from Business Process to Contract:a", label:"a",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 544, title:"from Business Process to Representation:a", label:"a",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 543, title:"from Business Process to Product:f", label:"f",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 502, title:"from Business Process to Application Component:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 501, title:"from Business Process to Application Collaboration:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 506, title:"from Business Process to Application Interface:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 504, title:"from Business Process to Application Function:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 505, title:"from Business Process to Application Interaction:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 507, title:"from Business Process to Application Process:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 503, title:"from Business Process to Application Event:tv", label:"tv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 508, title:"from Business Process to Application Service:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 525, title:"from Business Process to Data Object:fa", label:"a",arrows: "to",length: EDGE_LENGTH_MAIN}); 
      edges.push({from: 517, to: 538, title:"from Business Process to Node:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 527, title:"from Business Process to Device:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 548, title:"from Business Process to System Software:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 549, title:"from Business Process to Technology Collaboration:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 553, title:"from Business Process to Technology Interface:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 540, title:"from Business Process to Path:ft", label:"ft",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 521, title:"from Business Process to Communication Network:ft",label:"ft",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 551, title:"from Business Process to Technology Function:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 554, title:"from Business Process to Process Event:ftv", label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 552, title:"from Business Process to Technology Interaction:ftv",  label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 550, title:"from Business Process to Technology Event:tv", label:"tv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 557, title:"from Business Process to Technology Service:ftv",  label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 509, title:"from Business Process to Artifact:a",  label:"a",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 530, title:"from Business Process to Equipment:ftv",  label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 531, title:"from Business Process to Facility:ftv",  label:"ftv",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 528, title:"from Business Process to Distribution Network:ft",  label:"ft",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 536, title:"from Business Process to Material:a",  label:"a",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 547, title:"from Business Process to Stakeholder:in",  label:"in",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 529, title:"from Business Process to Driver:n", label:"n",arrows: "to",length: EDGE_LENGTH_MAIN}); 
      edges.push({from: 517, to: 510, title:"from Business Process to Assessment:n",  label:"n",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 533, title:"from Business Process to Goal:nr",  label:"nr",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 539, title:"from Business Process to Outcome:nr",  label:"nr",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 542, title:"from Business Process to Principle:nr", label:"nr",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 545, title:"from Business Process to Requirement:nr",  label:"nr",arrows: "to",length: EDGE_LENGTH_MAIN});
      edges.push({from: 517, to: 522, title:"from Business Process to Constraint:nr",  label:"nr",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 537, title:"from Business Process to Meaning:n",  label:"n",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 555, title:"from Business Process to Value:n", label:"n",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 556, title:"from Business Process to Work Package:o", label:"o",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 526, title:"from Business Process to Deliverable:o",  label:"o",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 534, title:"from Business Process to Implementation Event:o",  label:"o",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 541, title:"from Business Process to Plateau:o",  label:"o",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 532, title:"from Business Process to Gap:o", label:"o",arrows: "to",length: EDGE_LENGTH_MAIN});      
      edges.push({from: 517, to: 535, title:"from Business Process to Location:ft",  label:"ft",arrows: "to",length: EDGE_LENGTH_MAIN});  